### PR TITLE
Introduce `cime_run(ntsteps)`, callable for TSMP-PDAF

### PR DESCRIPTION
**Pull request by jjokella**
1. Re-introduce `private` statement, this was removed because variables from `cime_comp_mod` had to be used by TSMP-PDAF

2. Add `cime_run` with number of time steps `ntsteps` as input. `ntsteps` is supplied by the TSMP-PDAF interface.

3. Add `stop_alarm` for `cime_run` dependent on `ntsteps`.

### CODE REVIEW

**Comment by jjokella** [comment]
Draft status: Waiting for testing of corresponding TSMP-PR: https://github.com/HPSCTerrSys/TSMP/pull/229

**Comment by kvrigor** [comment]
@jjokella there are some changes here that overlap with #35; should that PR be already merged or do you prefer to have this PR merged instead?

**Comment by jjokella** [comment]
I merged #35, which makes the commit history of this PR a bit ugly. After squashing this PR, everything should be in order again!

**Comment by jjokella** [comment]
https://github.com/HPSCTerrSys/TSMP/pull/229 is tested and merged. All changes are under `#ifdef USE_PDAF`. So I propose merging this PR>

**Review by kvrigor — APPROVED** [review]

**Pull request merged**
