### PR TITLE
eCLM Documentation

### PR DESCRIPTION
**Pull request by odombro**
This pull request adds a documentation for eCLM to the repository by changing and adding files to the docs/ directory.
The new documentation includes a User's Guide with the following chapters:

- Introduction to eCLM
- Building eCLM
- Running example cases
- Creating a custom case
- Running eCLM
- Analyzing model output

### CODE REVIEW

**Comment by jjokella** [comment]
I have updated the `docs-initial` branch with 4 commits from `master`.

I plan to work through the documentation in the coming days with the goal of generating eCLM-PDAF data-assimilation testcases from the testcases discussed here.

What is the status of the PR? Could it be merged?

**Comment by kvrigor** [comment]
@jjokella there's a [discussion](https://github.com/HPSCTerrSys/eCLM_static_file_workflow/issues/2) on whether the **Custom case creation** docs should be moved to the [eCLM_static_file_workflow](https://github.com/HPSCTerrSys/eCLM_static_file_workflow) repo. Feel free to also share  your inputs there :)

**Comment by odombro** [comment]
Thanks for the review @jjokella. Regarding your comment on Prerequisites for JSC users, yes I am totally fine with that and also your other suggestions

**Comment by kvrigor** [comment]
> Building eCLM:JSC:Setting up eCLM: (1) MYPROJECT / MYSCRATCH not really needed!? Could be left out to make documentation more general. (2) Script load-eclm-variables.sh could be put in a shared folder as it is anyway very JSC-specific

Thanks for pointing this out @jjokella . I intend to fix the build part of the documentation on the next PR.

**Comment by kvrigor** [comment]
@s-poll @jjokella Can we already merge this? I'd suggest to do the improvements on the next pull requests. This PR is mainly for establishing the doc CI workflow and having a decent initial set of documentation which doesn't have to be super polished.

**Pull request merged**
