### PR TITLE
eCLM on Ubuntu2204 using github action 

### PR DESCRIPTION
**Pull request by kongdd**

### CODE REVIEW

**Comment by kongdd** [comment]
mct was updated to the latest to fix the issue of https://github.com/MCSclimate/MCT/issues/63

**Comment by kvrigor** [comment]
I didn't expect that this change also contains an upgrade to `MCT` and `mpi-serial`, which is quite nice! With the broader scope of this PR, I would need to test this further on our cluster. I'll get back on this once the tests are done.

**Comment by kvrigor** [comment]
> `mct` was updated to the latest to fix the issue of [MCSclimate/MCT#63](https://github.com/MCSclimate/MCT/issues/63)

I've verified it compiles successfully on our cluster. @kongdd kindly check the open reviews so I could finally merge this PR.

**Comment by kongdd** [comment]
Sorry, where can I found the reviews?

**Comment by kvrigor** [comment]
Within this PR page itself: gh_reviews

**Comment by kongdd** [comment]
fixed

**Pull request merged**
