### PR TITLE
Modify x2l instead of atm2lnd in eCLM

### PR DESCRIPTION
**Pull request by mvhulten**
See https://gitlab.jsc.fz-juelich.de/HPSCTerrSys/tsmp-internal-development-tracking/-/issues/29#note_231863

### CODE REVIEW

**Comment by kvrigor** [comment]
@mvhulten is this PR ready to be merged or is it still a draft? Also it would be nice to have the summary of changes in this PR (since our internal GitLab tracker isn't publicly accessible)

**Comment by mvhulten** [comment]
Thanks for picking this up, @kvrigor.

No, it not ready, so I marked it now as a draft.  This development is meant to be a refactoring, but after a few model hours of simulation fields are different from a simulation based on master (order of ±1 K for temperatures).  As discussed this morning with @spoll, we must first find the reason for this.  I'll update this merge request again when this is clear.

**Comment by mvhulten** [comment]
@spoll mentioned something about not cleanly replacing `atm2lnd` with `x2l`, but [this is done properly](https://github.com/HPSCTerrSys/eCLM/compare/master...mvhulten:eCLM:refac-x2l) as far as I can see.

Some whitespace edits were neither intentional nor necessary, though.

**Comment by mvhulten** [comment]
Reasons of differences are resolved and I made this [new pull request](!40).

**Pull request closed without merging**
